libraryVersion: 0.0.1-TESTING1
groupId: org.mozilla.telemetry
projects:
  glean-core:
    path: glean-core/android
    artifactId: glean-core
    publishedArtifacts: [glean-core, glean-core-forUnitTests, glean-core-withoutLib]
    description: 'The glean core library'
  glean-sample-app:
    path: samples/android/app
    artifactId: glean-core-sample-app
    description: 'An app demoing how to use the Glean library to collect and send telemetry data.'
