[workspace]

members = [
  "glean-core",
  "glean-core/rlb",
  "glean-core/bundle",
]

default-members = [
  "glean-core",
  "glean-core/rlb",
]

exclude = [
  "samples/multi-bindings"
]

[profile.release]
opt-level = "s"
debug = false
lto = true

[patch.crates-io]
uniffi = { git = "https://github.com/mozilla/uniffi-rs/" }
uniffi_macros = { git = "https://github.com/mozilla/uniffi-rs/" }
uniffi_build = { git = "https://github.com/mozilla/uniffi-rs/" }
