[package]
name = "glean-ffi"
edition = "2018"
version = "19.0.0"
authors = ["Jan-Erik Rediger <jrediger@mozilla.com>", "The Glean Team <glean-team@mozilla.com>"]

[lib]
name = "glean_ffi"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
lazy_static = "1.3.0"
ffi-support = "0.3.5"
log = "0.4.6"
uuid = { version = "0.7.4", features = ["v4"] }

[dependencies.glean-core]
path = ".."

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.7.0"

[target.'cfg(not(target_os = "android"))'.dependencies]
env_logger = { version = "0.6.2", default-features = false, features = ["termcolor", "atty", "humantime"] }
