[package]
name = "glean_ffi"
edition = "2018"
version = "0.1.0"
authors = ["Jan-Erik Rediger <jrediger@mozilla.com>"]

[lib]
name = "glean_ffi"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]

[dependencies.glean-core]
path = ".."

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.7.0"
