[package]
name = "glean_ffi"
edition = "2018"
version = "0.1.0"
authors = ["Jan-Erik Rediger <jrediger@mozilla.com>"]

[lib]
name = "glean_ffi"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
lazy_static = "1.3.0"
ffi-support = "0.3"
log = "0.4.6"

[dependencies.glean-core]
path = ".."

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.7.0"

[target.'cfg(not(target_os = "android"))'.dependencies]
env_logger = "0.6.1"
